[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
evm_version = "cancun"
optimizer_runs = 200

[fuzz]
max_test_rejects = 4294967295

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
